spring:
  application:
    name: order-system
  datasource:
    url: jdbc:postgresql://localhost:5432/order_system
    username: admin
    password: admin123
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    format-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  amqp:
    deserialization:
      trusted:
        packages: com.leonardo.order_system.entities