spring:
  application:
    name: order-system
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  amqp:
    deserialization:
      trusted:
        packages: com.leonardo.order_system.entities