spring:
  application:
    name: order-system
  datasource:
    url: jdbc:postgresql://localhost:5432/order_system
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  amqp:
    deserialization:
      trusted:
        packages: com.leonardo.order_system.entities